### ISSUE TITLE
Javascript Code coverage?

### ISSUE THREAD

**Issue by andrewhavens** [jfirebaugh/konacha#127]
Thanks for creating this great Rails engine. I really enjoy being able to test my javascript code in my Rails application.

This isn't really an "issue", but I didn't see any mention of a mailing list in the readme. I was wondering if you or anyone else has successfully generated code coverage reports for your Javascript code. Right now we're using SimpleCov to generate coverage reports for our Ruby code. Do you know of any such tool that would integrate well with konacha?

**Comment by pftg** [comment]
@andrewhavens  here is how we collect javascript test coverage by capybara https://jtway.co/collecting-javascript-code-coverage-with-capybara-in-ruby-on-rails-application-d0cb83a86a90 

maybe this will help you
