### ISSUE TITLE
Devise incompatibility issues

### ISSUE THREAD

**Issue by johngeorgewright** [jfirebaugh/konacha#162]
Hey there,

I've just tried installing **konacha** on a project I'm working on, but the **devise** gem starts to misbehave.

``` sh
$ bundle exec rake konacha:run
NoMethodError: undefined method `authenticate?' for nil:NilClass
    ~/.rvm/gems/ruby-1.9.3-p194@M3/gems/devise-2.1.2/lib/devise/controllers/helpers.rb:92:in `block in signed_in?'
```

I'm not much of a backend guy, but after a quick look around most people have a similar problem when installing **rspec** and use the following to get around it:

``` ruby
RSpec.configure do |config|
  config.include Devise::TestHelpers, :type => :controller
end
```

I tried adding that line (just in case) to the **konacha** initializer, but it made little difference.

``` ruby
Konacha.configure do |config|
  config.include Devise::TestHelpers, :type => :controller
end if defined? Konacha
```

Any ideas how I can get around this?

**Comment by techpeace** [comment]
Thanks for the workaround, @johngeorgewright! Quick note for others: the above `iframe` method should  be:

```ruby
    def iframe
      @spec = Konacha::Spec.find_by_name(params[:name])
      @stylesheets = Konacha::Engine.config.konacha.stylesheets
      @javascripts = Konacha::Engine.config.konacha.javascripts
    end
```
