### ISSUE TITLE
Net::ReadTimeout

### ISSUE THREAD

**Issue by tim-pg** [jfirebaugh/konacha#182]
Not a problem with Konacha per se, I would guess, but just throwing this out there in case anyone has any suggestions...

Running Konacha via selenium-webdriver, driving Firefox inside of xvfb (or xvnc, doesn't matter) on an Ubuntu box (with Jenkins CI), I keep getting this:

```
Net::ReadTimeout: Error communicating with browser process: Net::ReadTimeout
```

I've been getting this error off and on for a long time. So the suite was flaky but sorta worked (had to retry frequently with the Naginator plugin in Jenkins)... but recently it has gotten to where it always fails.

Perhaps related to this (?):
https://code.google.com/p/selenium/issues/detail?id=7642

Konacha started failing as of Firefox v32.0.1 (just released) due to the above issue, I think.  To address that, I updated selenium-webdriver to the latest version (2.43.0) so now it works fine when running Konacha via a Macbook Pro.  However on Ubuntu, it still dies from this timeout consistently. 

I've tried downgrading the Firefox back to version 28 on the Ubuntu CI box but no avail.

Any suggestions?

**Comment by dblackdblack** [comment]
I'm getting this same issue
