### ISSUE TITLE
Asset filtered out and will not be served

### ISSUE THREAD

**Issue by paneq** [jfirebaugh/konacha#194]
Following the instructions in README for `bundle exec rake konacha:serve` Rails 4.2 leads an error upon visiting the page in browser:

```
ActionView::Template::Error at /
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( konacha.css )` to `config/initializers/assets.rb` and restart your server
```

I had to add `config.assets.precompile += %w( konacha.css mocha.js konacha/parent.js chai.js konacha/iframe.js array_sum_spec.js)` in `development.rb` to make it work or

```
config.assets.precompile += %w( konacha.css mocha.js konacha/parent.js chai.js konacha/iframe.js)
config.assets.precompile += [/.*_spec\.js/]
```

Related:

* http://stackoverflow.com/questions/22970573/asset-filtered-out-and-will-not-be-served-add-config-assets-precompile

**Comment by paneq** [comment]
For `rake konacha:run` to work I had to add `konacha/runner.js` to the list as well

**Comment by jfirebaugh** [comment]
Konacha's default setting of [`app.config.assets.raise_runtime_errors = false`](https://github.com/jfirebaugh/konacha/commit/b3e4db99cc4890155f34048fffd81dfea9a5214b) disables this error. Have you overridden the default?
