### ISSUE TITLE
Need to override asset_host inside Konacha

### ISSUE THREAD

**Issue by ryana** [jfirebaugh/konacha#198]
Hey guys,

I ran into a problem where Konacha won't run on Jenkins. I've figured out what's going on, but I'm at a bit of a loss for how to proceed.

My app has subdomains, and there are some domain-based javascript-cookie games going on, so I need to set asset_host in development so that a request from `scrubber.ramen.dev` will retrieve assets from ramen.dev. For example: `ramen.dev/assets/widget.js`

Locally, I have no issue. All the Konacha tests run, but it's by accident. Here is what Konacha is serving:

```
<!doctype html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title>Konacha Tests</title>
    <link debug="false" href="//ramen.dev/assets/konacha.css" media="screen" rel="stylesheet" />
    <script debug="false" src="//ramen.dev/assets/mocha.js"></script>
<script debug="false" src="//ramen.dev/assets/konacha/parent.js"></script>
    <script debug="false" src="//ramen.dev/assets/konacha/runner.js"></script>
  </head>
```

Locally, that works fine because ramen.dev actually spins up the server locally, but on Jenkins, I don't have POW setup, so those assets cannot be loaded and this problem manifests.

If I remove this line from config/environments/development.rb, then the tests run successfully on Jenkins:
`config.action_controller.asset_host = "//ramen.dev"`

I'm not entirely sure how to proceed here. Doing this in config/environments/development.rb works, but boy is it ugly:

```
unless defined?(Capybara)
  config.action_controller.asset_host = "//ramen.dev"
end
```

Is there a better way or does Konacha need another config option?

**Comment by jfirebaugh** [comment]
You could use something more direct like `if ENV['JENKINS']`, but a conditional seems like the right approach to me.
