### ISSUE TITLE
undefined method `each_entry' for #<Sprockets::Environment:0x007fb129769378>

### ISSUE THREAD

**Issue by halogenandtoast** [jfirebaugh/konacha#203]
```
konacha (3.3.0) lib/konacha.rb:40:in `block in spec_paths'
Rails.application.assets.each_entry(root).find_all { |pathname|
```

It seems like each_entry was removed from sprockets a while ago:

https://github.com/rails/sprockets/commit/6c7b2dc045fbf7b77fe92246f47ae3eaf3c9c475

**Comment by alexauritt** [comment]
+1

**Comment by jasonben** [comment]
+1

**Comment by mbgardner** [comment]
+1

**Comment by shlub** [comment]
+1

**Comment by liuming** [comment]
Depends on your context, one possible way to get around this is to declare your sprockets dependency back to version 2.x

However if you have other gems or code has to rely on sprockets 3.x then you'll need the upstream fix.

**Comment by jonhyman** [comment]
https://github.com/uken/konacha/commit/adcdc81f198cc5a8f7a19e02c604fbfd6afa9b29 is the upstream commit that I merged into our fork which works for me.

**Comment by jonhyman** [comment]
@jfirebaugh, the commit from @uken lets it work with sprockets 3 so you don't need to force people to be on older versions of things.

**Comment by jfirebaugh** [comment]
Does it support sprockets 2.x as well? Can you or @uken please submit it as a pull request?

**Comment by jfirebaugh** [comment]
I pulled that commit in in 92a588daedacced4045b62354e35f7935997dc8d, but it causes [test failures](https://travis-ci.org/jfirebaugh/konacha/builds/61903389). I'd love it if someone submitted a PR that adds sprockets 3 support, but it needs to continue to pass tests and support sprockets 2 as well.

**Comment by jonhyman** [comment]
Let me see what I can do on Monday and get back to you with a pull perhaps.

**Comment by jonhyman** [comment]
@jfirebaugh check out https://github.com/jfirebaugh/konacha/pull/206. I ran the tests locally and they pass.
