### ISSUE TITLE
Unable to run Konacha in headless mode

### ISSUE THREAD

**Issue by niels-s** [jfirebaugh/konacha#205]
Hi there,

I'm having an issues with running Konacha in headless mode, but don't experience any issues with running the Konacha server.

    TypeError: Error communicating with browser process: no implicit conversion of Symbol into String
    ruby-2.2.2@S-M1/gems/colored-1.2/lib/colored.rb:70:in `colorize'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/formatter.rb:86:in `with_color'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/formatter.rb:23:in `example_failed'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/reporter.rb:64:in `block in process_event'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/reporter.rb:63:in `each'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/reporter.rb:63:in `process_event'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/reporter.rb:115:in `handle_mocha_fail'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/reporter.rb:47:in `process_mocha_event'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/runner.rb:28:in `block in run'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/runner.rb:26:in `each'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/runner.rb:26:in `run'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha/runner.rb:7:in `start'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/konacha.rb:21:in `run'
    ruby-2.2.2@S-M1/bundler/gems/konacha-adcdc81f198c/lib/tasks/konacha.rake:9:in `block (2 levels) in <top (required)>'

Probably this isn't an issue with the colorized gem because it's hasn't changed in quite some time. Wondering if somebody else is experiencing the same issue her?

I'm using the following dependencies:
- rails 4.2.1
- poltergeist 1.6.0
- konacha [https://github.com/jfirebaugh/konacha/issues/203](https://github.com/jfirebaugh/konacha/issues/203)

**Comment by jfirebaugh** [comment]
Can you provide a minimal self-contained example app that demonstrates the issue?

**Comment by spjsschl** [comment]
We had the same problem when using colorize 0.7.3 - it works with 0.7.7

the problem stems from passing colors as symbols as opposed to strings in konacha's formatter.rb.
I am nor sure how colorized and colored interact (since the exception is raised from colored)

**Comment by spjsschl** [comment]
I experienced the same problem today when using 'colorize', '0.7.7' it worked with 0.7.3

**Comment by niels-s** [comment]
@spjsschl downgrading `colorize` to version `0.7.3` also does the trick for me at least for the time being.
@jfirebaugh Didn't find the time yet to setup a project to share or investigate any further. Hope I find some time soon, I know it has been a while since I reported it :disappointed:

**Comment by nerdinand** [comment]
I used to have the same problem, but it seems to be gone now... Using:
* rails 4.2.4
* konacha 3.7.0
* poltergeist 1.7.0
* colorize 0.7.7

**Comment by jfirebaugh** [comment]
Closing since no test case was provided. Feel free to reopen if you make one.
