### ISSUE TITLE
How do I use Konacha when testing gemified javascript

### ISSUE THREAD

**Issue by JohnSmall** [jfirebaugh/konacha#210]
I've created a nice little Coffeescript class with full Konacha tests. Now I want to turn it into a gem so I can easily use it in other projects and other people can also use it. But..

When I create a gem and add Konacha as a development dependency then I don't see the rake tasks added to the list of tasks, so I can't run the tests.

How can I use Konacha when testing javascript/coffeescript in a gem?

**Comment by jfirebaugh** [comment]
Does https://github.com/jfirebaugh/konacha/issues/46#issuecomment-6818549 help?

**Comment by JohnSmall** [comment]
That looks like a complete answer. I'll check it out, thanks
