### ISSUE TITLE
Require commonjs module, e.g. export.default

### ISSUE THREAD

**Issue by ivawzh** [jfirebaugh/konacha#224]
I want to test my javascript in a dependency injection manner, e.g. 

```
_ = require('lodash')
describe('lodash should work', ....)
```
Is there anyway that I can use commonjs's module require in Konacha?
I know `//= require` can load file, but how do I assign the loaded file/method to a variable?
Cheers

**Comment by jfirebaugh** [comment]
Konacha is built on top of the Rails asset pipeline. You will need to investigate ways of using CommonJS with the asset pipeline.
