### ISSUE TITLE
Add an easy way to bind konacha server to 0.0.0.0

### ISSUE THREAD

**Issue by snird** [jfirebaugh/konacha#227]
First, sorry if such a way exists, but I couldn't find it.

Running konacha from vagrant machine (or, any VM) requires running the web server with bind to `0.0.0.0` (or any specific route) instead of `127.0.0.1` so that using the VM port-forwarding, it will be available from the host computer.
This might not be the case for every dev machine, so there needs to be some easy way to configure it from the running command. 
Something like: `rake konacha:serve BIND=0.0.0.0`

**Comment by jfirebaugh** [comment]
Try this in your `config/initializers/konacha.rb`:

```
Konacha.configure do |config|
  config.port     = "0.0.0.0"
end if defined?(Konacha)
```

**Comment by snird** [comment]
Hi @jfirebaugh , thanks for the quick reply.
I knew about the configuration settings, what I meant by this issue, is that a CLI config might be needed here.
As I wrote, not all developers work with a VM, and so, for obvious reasons, we don't want `0.0.0.0` to be the default. This is why a way to configure it directly when running the command seems like a good solution.

**Comment by jfirebaugh** [comment]
You can do something like:

```
Konacha.configure do |config|
  config.port = ENV['PORT'] || '127.0.0.1'
end if defined?(Konacha)
```

and  `PORT=0.0.0.0 rake konacha:serve`
